$(function(){
	$(document).ready(function(){
		$(".coverpic_a").hover(function(){
			$(".text_a").fadeIn();
			$(".pic_a").fadeIn();
		},function(){});
		$(".pic_a").hover(function(){},function(){
			$(".text_a").fadeOut();
			$(".pic_a").fadeOut();			
		});
		$(".coverpic_b").hover(function(){
			$(".text_b").fadeIn();
			$(".pic_b").fadeIn();
		},function(){});
		$(".pic_b").hover(function(){},function(){
			$(".text_b").fadeOut();
			$(".pic_b").fadeOut();			
		});
		$(".coverpic_c").hover(function(){
			$(".text_c").fadeIn();
			$(".pic_c").fadeIn();
		},function(){});
		$(".pic_c").hover(function(){},function(){
			$(".text_c").fadeOut();
			$(".pic_c").fadeOut();			
		});
		$(".coverpic_d").hover(function(){
			$(".text_d").fadeIn();
			$(".pic_d").fadeIn();
		},function(){});
		$(".pic_d").hover(function(){},function(){
			$(".text_d").fadeOut();
			$(".pic_d").fadeOut();			
		});
		$(".coverpic_e").hover(function(){
			$(".text_e").fadeIn();
			$(".pic_e").fadeIn();
		},function(){});
		$(".pic_e").hover(function(){},function(){
			$(".text_e").fadeOut();
			$(".pic_e").fadeOut();			
		});
		
	});
});
